// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MoveHandlerClient is the client API for MoveHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoveHandlerClient interface {
	GetMove(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Data, error)
}

type moveHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewMoveHandlerClient(cc grpc.ClientConnInterface) MoveHandlerClient {
	return &moveHandlerClient{cc}
}

func (c *moveHandlerClient) GetMove(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/move.MoveHandler/GetMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoveHandlerServer is the server API for MoveHandler service.
// All implementations must embed UnimplementedMoveHandlerServer
// for forward compatibility
type MoveHandlerServer interface {
	GetMove(context.Context, *Params) (*Data, error)
	mustEmbedUnimplementedMoveHandlerServer()
}

// UnimplementedMoveHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedMoveHandlerServer struct {
}

func (UnimplementedMoveHandlerServer) GetMove(context.Context, *Params) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMove not implemented")
}
func (UnimplementedMoveHandlerServer) mustEmbedUnimplementedMoveHandlerServer() {}

// UnsafeMoveHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoveHandlerServer will
// result in compilation errors.
type UnsafeMoveHandlerServer interface {
	mustEmbedUnimplementedMoveHandlerServer()
}

func RegisterMoveHandlerServer(s grpc.ServiceRegistrar, srv MoveHandlerServer) {
	s.RegisterService(&MoveHandler_ServiceDesc, srv)
}

func _MoveHandler_GetMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveHandlerServer).GetMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/move.MoveHandler/GetMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveHandlerServer).GetMove(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

// MoveHandler_ServiceDesc is the grpc.ServiceDesc for MoveHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoveHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "move.MoveHandler",
	HandlerType: (*MoveHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMove",
			Handler:    _MoveHandler_GetMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moves.proto",
}
